import Head from "next/head";
import ApexChart from "../components/Chart";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ApexChart />
    </div>
  );
}
